### ISSUE TITLE
restore not working after reboot

### ISSUE THREAD

**Issue by kkmaslowski** [jaszhix/icingwindowsaver#1]
Hi! First thanks for creating very useful applet. 
I have one problem with it - window restore does not work after reboot. Nothing happens when I select it. It works great for current session only. 
My setup: Fedora 25, Cinnamon 3.2.

**Comment by jaszhix** [comment]
Its a current limitation of this implementation. Its saving just the window IDs which get reset after each session. Fixing this would require rewriting it, which I won't rule out, but would take some time.
